export const REGISTER_USER_TYPE = "REGISTER_USER";
export const LOGIN_USER_TYPE = "LOGIN_USER";
export const AUTH_ERR_TYPE = "AUTH_ERR";
export const SET_USER_TYPE = "SET_USER";

export const SET_COLLECTION_TYPE = "SET_COLLECTION";
export const CREAT_COLLECTION_TYPE = " CREAT_COLLECTION";