export const REGISTER_USER_TYPE = "REGISTER_USER";
export const LOGIN_USER_TYPE = "LOGIN_USER";
export const AUTH_ERR_TYPE = "AUTH_ERR";
export const SET_USER_TYPE = "SET_USER";

export const SET_COLLECTION_TYPE = "SET_COLLECTION";
export const SET_ACTIVE_COLLECTION_TYPE = "SET_ACTIVE_COLLECTION"
export const CREAT_COLLECTION_TYPE = " CREAT_COLLECTION";
export const UPLOAD_COLLECTION_IMG_TYPE = "UPLOAD_COLLECTION_IMG";
export const DELETE_COLLECTION_TYPE = "DELETE_COLLECTION";
export const UPDATE_COLLECTiON_TYPE = "UPDATE_COLLECTION";

export const SET_POSTS_TYPE = "SET_POSTS";
export const PUBLISH_POSTS_TYPE = "PUBLISH_POSTS";
export const UNPUBLISH_POSTS_TYPE = "UNPUBLISH_POSTS";
export const DELETE_POSTS_TYPE = "DELETE_POSTS";
export const SET_ACTIVE_POSTS_TYPE = "SET_ACTIVE_POSTS";

export const SET_PROFILE_TYPE = "SET_PROFILE";
export const CREATE_PROFILE_TYPE = "CREATE_PROFILE";